spring.application.name=lab5

spring.datasource.url=jdbc:mysql://localhost:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DemoProduct;encrypt=true;trustServerCertificate=true
# spring.datasource.username=sa
# spring.datasource.password=123456

# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true